name: "Github Actions Test"

on:
  workflow_dispatch:
    inputs:
      text:
        description: "Please enter the word to be printed"
        default: "Hello"
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Get the repository name"
        run: echo "Repo: ${{ github.repository }}"

      - name: "Get the github actor"
        run: echo "Triggered by: ${{ github.actor }}"
